version: "3"
services:
  web:
    restart: on-failure:10
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #command: newrelic-admin run-program gunicorn appointmentguru.wsgi:application -b :8000 --reload
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

