version: "3"
services:
  db:
    restart: on-failure:10
    image: postgres:9.5
    volumes:
      - "invoiceguru-postgres-db-volume:/var/lib/postgresql/data"
      - ./appointmentguru.sql:/code/appointmentguru.sql
      - ./medicalaidguru.sql:/code/medicalaidguru.sql
      - ./invoiceguru.sql:/code/invoiceguru.sql

  # dependencies:
  appointmentguru:
    image: appointmentguru/appointmentguru:swarm
    command: sh /code/run.sh
    env_file:
      - env.dev
    ports:
      - "8003:80"

  medicalaidguru:
    image: appointmentguru/medicalaidguru:latest
    command: sh /code/run.sh
    env_file:
      - env.dev
    environment:
      - DATABASE_NAME=appointmentguru_medicalaidguru
    ports:
      - "8002:80"

  communicationguru:
    image: appointmentguru/communicationguru:unibox
    command: sh /code/run.sh
    env_file:
      - env.dev
    environment:
      - DATABASE_NAME=appointmentguru_communicationguru
    ports:
      - "8000:80"
  # app:
  web:
    restart: on-failure:10
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #command: newrelic-admin run-program gunicorn appointmentguru.wsgi:application -b :8000 --reload
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file:
      - env.dev
    environment:
      - DATABASE_NAME=appointmentguru_invoiceguru

volumes:
  invoiceguru-postgres-db-volume:
